### ISSUE TITLE
Consider FChT for f0 estimation and harmonic analysis

### ISSUE THREAD

**Issue by tuxzz** [Sleepwalking/libllsm2#1]
## Problems that we have now:
1. PYin is not robust and accurate enough on signal with low SNR at small window(4 * T), we have to fix some frames manually.
    For example, [tuxzz/revoice_prototype/yuri_orig](https://github.com/tuxzz/revoice_prototype/blob/master/voices/yuri_orig.wav), where [0.19s, 0.354s), [2.669s, 2.689s), [2.814s, 2.86s) should be voiced but pyin marked it unvoiced and give a poor predicted f0 value.
    It may be a good choice to use FChT-based method[2] or the SRH(Summation of Residual Harmonics) based method to get better F0 and voice activity.
2. Our current harmonic analysis method isn't really perfect. Even if Chirp-Z and Direct-DFT[4] are more better than FFT spectrum-based method.
    We can't even reconstruct a clean linear chirp or stationary harmonic signal perfectly due to inaccurate f0 and imperfect harmonic analysis-synthesis method.
    FChT provided a method to analysis chirp signal near-perfectly, we can have better resolution on both time and frequency axes, which can give out a better analysis result.
3. 0.005s for hop size is not enough for signals with very fast variant f0, which is common on talking voice.
   0.0025s is good on both quality and speed.  

By the way, a chirp harmonic model maybe better than our current model.

## References
* [1] Weruaga, Luis, and Márian Képesi. "The fan-chirp transform for non-stationary harmonic signals." Signal Processing 87.6 (2007): 1504-1522.
* [2] Cancela, Pablo, Ernesto López, and Martín Rocamora. "Fan chirp transform for music representation." 13th Int. Conf. on Digital Audio Effects, Austria. 2010.
* [3] Dunn, Robert, and Thomas F. Quatieri. "Sinewave analysis/synthesis based on the Fan-Chirp tranform." Applications of Signal Processing to Audio and Acoustics, 2007 IEEE Workshop on. IEEE, 2007.
* [4] Direct-DFT is a modified DFT. Normal DFT is ![image](https://chart.googleapis.com/chart?cht=tx&chl=\hat{x}[k]=\sum_{n=0}^{N-1}%20e^{-i\frac{2\pi}{N}nk}x[n]) and Direct-DFT is ![image](https://chart.googleapis.com/chart?cht=tx&chl=\hat{x}[k]=\sum_{n=0}^{N-1}%20e^{-i\frac{2f\pi}{f_s}n}x[n]), where f is frequency, fs is sample rate, allows you calculate any frequency point from a signal. It works better than czt on my program.

**Comment by Sleepwalking** [comment]
Hello,

Sorry for my delayed response. I appreciate your efforts on investigating the defects of *libllsm2* with connections to a broader context of harmonic modeling techniques.

The use of FChT in fact has been evaluated before the *libllsm* -> *libllsm2* upgrade, although the attempt wasn't properly documented. I did not observe a significant improvement compared to 3-period CZT. It was possible that the harmonic analysis accuracy had saturated due to fine errors in F0 analysis, and this hypothesis prompted me to [YANG](https://github.com/google/yang_vocoder) F0 analysis method (and its improved versions).

My take on the speech harmonic analysis problem is to view it as a dual problem of (1) estimating the harmonic component and (2) estimating the noise component. Accurate extraction of either constituent would guarantee the accurate extraction of the other by model definition. However, without assuming the existence of an additive noise component, the harmonic model would overfit onto the noise part (as exemplified in various extensions to the least-squares analysis, such as QHM, aHM, etc, although they can't be blamed since they were not designed to meaningfully characterize noise). As for conventional Fourier analysis techniques (e.g. DFT, CZT), the degree of overfit can be characterized by calculating p(X[k] | SNR), where X[k] are FFT bins, and you'll get Gaussian results and closed forms for the means and variances. I have not yet attempted this on FChT which involves a non-linear warping operation.

Please note that the linking with *libpyin* in the tests is for demonstrative purposes. I do recommend switching to a more accurate F0 estimator and turn off `llsm_aoptions.f0_refine`.

> It [Direct-DFT] works better than czt on my program.

The results from DTFT and CZT should be the same, albeit the later is subjected to larger numerical errors. There is a [test](https://github.com/Sleepwalking/ciglet/blob/master/test/test.c#L78) in *ciglet* that compares CZT with FFT. The errors may differ due to different compiler flags.

**Comment by Sleepwalking** [comment]
Issue closed due to inactivity.
